# Generated by Django 3.1 on 2020-09-06 08:32

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='movie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('desc', models.TextField()),
                ('time_start', models.TimeField()),
                ('time_end', models.TimeField()),
                ('bookings', models.IntegerField()),
                ('thumbnail', models.ImageField(upload_to='')),
                ('booked', django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), default=list, size=20)),
            ],
        ),
        migrations.CreateModel(
            name='ticket',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movie', models.CharField(max_length=200)),
                ('book_time', models.TimeField()),
                ('user', models.CharField(max_length=200)),
                ('phone', models.CharField(max_length=15)),
                ('nos', models.IntegerField()),
            ],
        ),
    ]
