# Generated by Django 3.1 on 2020-09-06 14:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0002_ticket_booked'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ticket',
            old_name='booked',
            new_name='seats',
        ),
    ]
